apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "elastalert.fullname" . }}-config-cm
  labels:
    {{- include "elastalert.labels" . | nindent 4 }}
data:
{{- range $key, $value := .Values.elast_config }}
{{ $key | indent 2}}: |-
{{ $value | indent 4}}
{{- end }}
