{{- if .Values.use_smtp_credentials }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "elastalert.fullname" . }}-smtpcredentials-secret
  labels:
    {{- include "elastalert.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $key, $value := .Values.elast_smtp_credentials }}
{{ $key | indent 2}}: |-
{{ $value | b64enc | indent 4}}
{{- end }}
{{- end }}
